In [93]:
import numpy as np

In [94]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [101]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [100]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [105]:
np.linspace(0,10,3) #like make it a slices from beggining 0 to the endding 10

array([ 0.,  5., 10.])

In [107]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
np.random.rand(2)

array([0.49928637, 0.3202268 ])

In [110]:
np.random.rand(5, 5)

array([[0.88449443, 0.80174403, 0.5848368 , 0.44589962, 0.01680127],
       [0.09197602, 0.75959967, 0.60583415, 0.0332883 , 0.70042386],
       [0.0797274 , 0.37231004, 0.48072274, 0.41084733, 0.49965246],
       [0.69805912, 0.00635202, 0.80760601, 0.43075845, 0.78641808],
       [0.13283264, 0.29508409, 0.19886075, 0.67880595, 0.33021755]])

In [112]:
np.random.randint(1, 100) #choose random number from 1 to 100

77

In [115]:
np.random.randint(1, 100, 10) #choose 10 random number from 1 to 100

array([48, 15, 13, 61, 63, 40, 21, 27, 94, 57])

In [119]:
arr = np.random.randint(1, 100, 25)
arr = arr.reshape(5,5) # reshape this array to a 5x5 matrix
print(arr)

[[20 35  6 94  7]
 [45 12  3 33 38]
 [93 24 30 20 83]
 [ 6 18 62  9 67]
 [34 27 78 49  1]]


In [121]:
arr.min()

1

In [123]:
arr.argmin() #index of the min value

24

In [124]:
arr.max()

94

In [125]:
arr.argmax() #index of the max value

3

In [126]:
arr.reshape(-1,1) #reshape to a 1d array

array([[20],
       [35],
       [ 6],
       [94],
       [ 7],
       [45],
       [12],
       [ 3],
       [33],
       [38],
       [93],
       [24],
       [30],
       [20],
       [83],
       [ 6],
       [18],
       [62],
       [ 9],
       [67],
       [34],
       [27],
       [78],
       [49],
       [ 1]])

In [127]:
arr.dtype

dtype('int64')

In [128]:
arr.shape

(5, 5)

In [134]:
arr_ = np.arange(0, 9).reshape(3,3)
arr_

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
arr___ = arr_.copy()
arr___

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [139]:
arr___[:] = 99 #make all elements = 99
arr___

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])